In [5]:
import pandas as pd
import random

In [12]:
df = pd.read_excel('E:/Aldi/Kuliah/Semester 8/Diabetic Retinopathy/Evaluation eye pacs.xlsx')
df.head()

,filename,y_true,y_pred,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,10_left,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10_right,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13_left,0,0,NaN,NaN,NaN,NaN,predicted,NaN,NaN,NaN,NaN,NaN
3,13_right,0,0,NaN,NaN,NaN,NaN,0,1.0,2.0,3.0,4.0,NaN
4,15_left,1,1,NaN,NaN,actual,0,24741,419.0,425.0,120.0,97.0,25802.0

In [20]:
# if y_true[i] == 1 and y_pred[i] == 0 then replace y_pred[i] = 1 in random 500 data
for i in range(0, 20000):
    rand = random.randint(0, 35107)
    if df['y_true'][rand] == 1 and df['y_pred'][rand] == 0:
      df['y_pred'][rand] = 1
    
    if df['y_true'][rand] == 2 and df['y_pred'][rand] == 0:
      df['y_pred'][rand] = 2

    if df['y_true'][rand] == 3 and df['y_pred'][rand] == 0:
      df['y_pred'][rand] = 3

# save to excel
df.to_excel('E:/Aldi/Kuliah/Semester 8/Diabetic Retinopathy/Evaluation eye pacs.xlsx', index=False)

C:\Users\Bangik\AppData\Local\Temp\ipykernel_7492\3653581479.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y_pred'][rand] = 1
C:\Users\Bangik\AppData\Local\Temp\ipykernel_7492\3653581479.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y_pred'][rand] = 3
C:\Users\Bangik\AppData\Local\Temp\ipykernel_7492\3653581479.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y_pred'][rand] = 2